# Generated by Django 5.0.6 on 2025-11-11 00:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('nome_fantasia', models.CharField(max_length=120)),
                ('uf', models.CharField(max_length=2)),
                ('csc_id', models.CharField(max_length=50)),
                ('csc_token', models.CharField(max_length=100)),
                ('a1_pfx', models.BinaryField(blank=True, null=True)),
                ('a1_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ambiente', models.CharField(default='homolog', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
