# Generated by Django 5.0.6 on 2025-11-18 14:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(help_text='Razão social da empresa emitente (xNome).', max_length=120)),
                ('nome_fantasia', models.CharField(help_text='Nome fantasia da filial (xFant).', max_length=120)),
                ('cnpj', models.CharField(db_index=True, help_text='CNPJ da filial (somente números, 14 dígitos).', max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14)])),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Indica se a filial está ativa para emissão.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endereco', models.ForeignKey(help_text='Endereço fiscal da filial (enderEmit na NFe).', on_delete=django.db.models.deletion.PROTECT, related_name='filiais', to='enderecos.endereco')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='FilialCertificadoA1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1_pfx', models.BinaryField(help_text='Arquivo PFX do certificado A1, criptografado.')),
                ('senha_hash', models.CharField(help_text='Hash ou dado cifrado da senha do certificado.', max_length=255)),
                ('a1_expires_at', models.DateTimeField(help_text='Data de expiração do certificado A1.')),
                ('numero_serie', models.CharField(blank=True, help_text='Número de série do certificado (opcional, para conferência).', max_length=100)),
                ('emissor', models.CharField(blank=True, help_text='Emissor (CA) do certificado (opcional).', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.OneToOneField(help_text='Filial cujo certificado A1 é usado para assinar NF-e/NFC-e.', on_delete=django.db.models.deletion.CASCADE, related_name='certificado_a1', to='filial.filial')),
            ],
            options={
                'verbose_name': 'Certificado A1 da Filial',
                'verbose_name_plural': 'Certificados A1 das Filiais',
            },
        ),
        migrations.CreateModel(
            name='FilialFiscalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao_estadual', models.CharField(blank=True, help_text='Inscrição Estadual (IE) da filial, se houver.', max_length=14)),
                ('inscricao_municipal', models.CharField(blank=True, help_text='Inscrição Municipal, se emitir NF de serviços.', max_length=15)),
                ('cnae_principal', models.CharField(blank=True, help_text='CNAE fiscal principal (somente números).', max_length=9)),
                ('regime_tributario', models.CharField(choices=[('1', 'Simples Nacional'), ('2', 'Simples Nacional - excesso de sublimite'), ('3', 'Regime Normal')], default='1', help_text='Regime tributário (CRT) usado na NF-e/NFC-e.', max_length=1)),
                ('tipo_contrib_icms', models.CharField(choices=[('1', 'Contribuinte ICMS'), ('2', 'Isento'), ('9', 'Não contribuinte')], default='1', help_text='Tipo de contribuinte de ICMS da filial.', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.OneToOneField(help_text='Filial a que esta configuração fiscal pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_config', to='filial.filial')),
            ],
            options={
                'verbose_name': 'Configuração Fiscal da Filial',
                'verbose_name_plural': 'Configurações Fiscais das Filiais',
            },
        ),
        migrations.CreateModel(
            name='FilialNFCeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(choices=[('homolog', 'Homologação'), ('producao', 'Produção')], default='homolog', help_text='Ambiente padrão de emissão de NFC-e.', max_length=12)),
                ('csc_id', models.CharField(help_text='Identificador do CSC fornecido pela SEFAZ.', max_length=50)),
                ('csc_token', models.CharField(help_text='Token do CSC fornecido pela SEFAZ (usado no QR-Code).', max_length=100)),
                ('modelo_impressao', models.CharField(default='TERMICA80', help_text='Configuração padrão de impressão do DANFE NFC-e (uso interno).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.OneToOneField(help_text='Filial a que esta configuração de NFC-e pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='nfce_config', to='filial.filial')),
            ],
            options={
                'verbose_name': 'Configuração NFC-e da Filial',
                'verbose_name_plural': 'Configurações NFC-e das Filiais',
            },
        ),
        migrations.CreateModel(
            name='FilialNFeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(choices=[('homolog', 'Homologação'), ('producao', 'Produção')], default='homolog', help_text='Ambiente padrão de emissão de NF-e (homologação/produção).', max_length=12)),
                ('natureza_operacao_padrao', models.CharField(default='VENDA DE MERCADORIA', help_text='Natureza de operação padrão da NF-e (natOp).', max_length=60)),
                ('versao_layout', models.CharField(default='4.00', help_text='Versão do layout da NF-e utilizada (ex.: 4.00).', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.OneToOneField(help_text='Filial a que esta configuração de NF-e pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='nfe_config', to='filial.filial')),
            ],
            options={
                'verbose_name': 'Configuração NF-e da Filial',
                'verbose_name_plural': 'Configurações NF-e das Filiais',
            },
        ),
        migrations.AddIndex(
            model_name='filial',
            index=models.Index(fields=['cnpj'], name='idx_filial_cnpj'),
        ),
        migrations.AddIndex(
            model_name='filial',
            index=models.Index(fields=['ativo'], name='idx_filial_ativo'),
        ),
    ]
