# Generated by Django 5.0.6 on 2025-11-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filialnfceconfig',
            name='external_api_key_alias',
            field=models.CharField(blank=True, help_text='Alias/identificador da credencial no cofre de segredos. Não armazena a chave em texto puro no banco.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='filialnfceconfig',
            name='external_company_id',
            field=models.CharField(blank=True, help_text='Identificador da empresa na API fiscal externa (ex.: ID na NDD).', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='filialnfceconfig',
            name='external_endpoint_base',
            field=models.URLField(blank=True, help_text='URL base da API fiscal externa utilizada para NFC-e nesta filial.', null=True),
        ),
        migrations.AddField(
            model_name='filialnfceconfig',
            name='provider',
            field=models.CharField(choices=[('ndd', 'NDD'), ('proprio', 'API Própria'), ('outro', 'Outro Provider')], default='ndd', help_text='Provider de emissão fiscal para NFC-e (NDD, API própria, etc).', max_length=20),
        ),
    ]
