# Generated by Django 5.0.6 on 2025-11-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0002_filialnfceconfig_external_api_key_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='percentual_maximo_desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual máximo de desconto permitido para esta filial.', max_digits=5),
        ),
    ]
