# Generated by Django 5.0.6 on 2025-11-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0003_filial_percentual_maximo_desconto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filial',
            old_name='percentual_maximo_desconto',
            new_name='desconto_maximo_percentual',
        ),
    ]
