# Generated by Django 5.0.6 on 2025-11-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0004_rename_percentual_maximo_desconto_filial_desconto_maximo_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filial',
            name='desconto_maximo_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Percentual máximo de desconto permitido para esta filial.', max_digits=5, null=True),
        ),
    ]
