# Generated by Django 5.0.6 on 2025-11-26 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0005_alter_filial_desconto_maximo_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='casas_decimais_preco_display',
            field=models.PositiveSmallIntegerField(choices=[(2, '2 casas decimais (padrão; moeda)'), (3, '3 casas decimais'), (4, '4 casas decimais')], default=2, help_text='Quantidade de casas decimais para exibição de preços no PDV. O backend continuará calculando internamente com maior precisão; esta configuração afeta apenas apresentação e arredondamento em tela.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
