# Generated by Django 5.0.6 on 2025-11-26 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0006_filial_casas_decimais_preco_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='ie',
            field=models.CharField(default='ISENTO', help_text='Inscrição Estadual da filial (IE).', max_length=14, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='filial',
            name='im',
            field=models.CharField(blank=True, help_text='Inscrição Municipal da filial (IM).', max_length=15, null=True),
        ),
    ]
