# Generated by Django 5.0.6 on 2025-11-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0007_filial_ie_filial_im'),
    ]

    operations = [
        migrations.AddField(
            model_name='filialfiscalconfig',
            name='aliquota_cofins',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Alíquota de COFINS (%) aplicada nas operações da filial.', max_digits=5),
        ),
        migrations.AddField(
            model_name='filialfiscalconfig',
            name='aliquota_pis',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Alíquota de PIS (%) aplicada nas operações da filial.', max_digits=5),
        ),
    ]
