# Generated by Django 5.0.6 on 2025-11-24 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0004_rename_percentual_maximo_desconto_filial_desconto_maximo_percentual'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, help_text='Código interno do método de pagamento (até 7 caracteres).', max_length=7, unique=True)),
                ('tipo', models.CharField(choices=[('DIN', 'Dinheiro'), ('PIX', 'PIX'), ('CRC', 'Cartão de Crédito'), ('CRD', 'Cartão de Débito'), ('VCH', 'Voucher / Refeição'), ('OUT', 'Outros')], help_text='Tipo lógico do método (dinheiro, PIX, crédito, débito, etc).', max_length=3)),
                ('descricao', models.CharField(max_length=255)),
                ('utiliza_tef', models.BooleanField(default=False, help_text='Indica se este método utiliza TEF/SITEF.')),
                ('codigo_fiscal', models.CharField(help_text="Código da forma de pagamento no XML (ex: '01'=Dinheiro, '03'=Cartão de Crédito).", max_length=2)),
                ('codigo_tef', models.CharField(blank=True, help_text='Código equivalente no TEF/SITEF, se aplicável.', max_length=10, null=True)),
                ('desconto_maximo_percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de desconto automático ao usar este método.', max_digits=5, null=True)),
                ('permite_parcelamento', models.BooleanField(default=False)),
                ('max_parcelas', models.PositiveSmallIntegerField(default=1)),
                ('valor_minimo_parcela', models.DecimalField(blank=True, decimal_places=2, help_text='Valor mínimo permitido por parcela, se parcelamento for permitido.', max_digits=10, null=True)),
                ('permite_troco', models.BooleanField(default=True, help_text='Indica se esse método permite troco (normalmente só dinheiro).')),
                ('ordem_exibicao', models.PositiveSmallIntegerField(default=0)),
                ('permite_desconto', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de Pagamento',
                'verbose_name_plural': 'Métodos de Pagamento',
                'db_table': 'metodo_pagamento',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FilialMetodoPagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o método está ativo nesta filial.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(help_text='Filial em que o método de pagamento está disponível.', on_delete=django.db.models.deletion.CASCADE, related_name='filiais_metodos_pagamento', to='filial.filial')),
                ('metodo_pagamento', models.ForeignKey(help_text='Método de pagamento disponível nesta filial.', on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pagamento_filiais', to='metodoPagamento.metodopagamento')),
            ],
            options={
                'verbose_name': 'Método de Pagamento por Filial',
                'verbose_name_plural': 'Métodos de Pagamento por Filial',
                'db_table': 'filial_metodo_pagamento',
                'indexes': [models.Index(fields=['filial'], name='idx_filial_met_pgto_filial'), models.Index(fields=['metodo_pagamento'], name='idx_filial_met_pgto_metodo'), models.Index(fields=['ativo'], name='idx_filial_met_pgto_ativo')],
            },
        ),
        migrations.AddConstraint(
            model_name='filialmetodopagamento',
            constraint=models.UniqueConstraint(fields=('filial', 'metodo_pagamento'), name='uniq_filial_met_pagamento'),
        ),
    ]
