# Generated by Django 5.0.6 on 2025-11-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
