# Generated by Django 5.0.6 on 2025-11-19 19:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal', '0002_cest_ncm_ncm_uniq_ncm_codigo_vigencia_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sigla', models.CharField(help_text='Sigla da unidade (ex: UN, KG, CX, M, L, PCT...)', max_length=6, unique=True)),
                ('descricao', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('COMERCIAL', 'Comercial'), ('TRIBUTARIA', 'Tributária'), ('GERAL', 'Geral')], default='GERAL', help_text='Classificação principal de uso da unidade.', max_length=20)),
                ('fator_conversao', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Fator de conversão em relação à unidade base (se aplicável).', max_digits=12)),
                ('eh_padrao', models.BooleanField(default=False, help_text='Indica se esta unidade é uma das unidades padrão do sistema.')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='GrupoProduto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_index=True, help_text='Nome do grupo de produtos (ex.: Bebidas, Higiene, Padaria).', max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True, default='', help_text='Descrição opcional do grupo para uso interno.')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem/ícone deste grupo para exibição no app.', null=True, upload_to='grupos_produtos/')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o grupo está disponível para uso em cadastros e vendas.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo de Produto',
                'verbose_name_plural': 'Grupos de Produtos',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['ativo'], name='idx_grupo_prod_ativo')],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_interno', models.CharField(help_text='Código interno/SKU do produto.', max_length=40, unique=True)),
                ('descricao', models.CharField(help_text='Descrição principal do produto (xProd).', max_length=255)),
                ('descricao_complementar', models.TextField(blank=True, default='', help_text='Descrição complementar/observações internas.')),
                ('fator_conversao_tributavel', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Fator de conversão entre a unidade comercial e a unidade tributável. Ex: 1 CX = 12 UN -> fator = 12.000000', max_digits=12)),
                ('peso_liquido_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text="Peso líquido em kg (tag 'qCom * peso_unitário', quando aplicável).", max_digits=11)),
                ('peso_bruto_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Peso bruto em kg para cálculo de frete/logística.', max_digits=11)),
                ('origem_mercadoria', models.CharField(choices=[('0', '0 - Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8'), ('1', '1 - Estrangeira - Importação direta'), ('2', '2 - Estrangeira - Adquirida no mercado interno'), ('3', '3 - Nacional, com conteúdo de importação superior a 40%'), ('4', '4 - Nacional, cuja produção tenha sido feita em conformidade com PPB'), ('5', '5 - Nacional, com conteúdo de importação inferior ou igual a 40%'), ('6', '6 - Estrangeira - Importação direta, sem similar nacional'), ('7', '7 - Estrangeira - Adquirida no mercado interno, sem similar nacional'), ('8', '8 - Nacional, conteúdo de importação superior a 70%')], default='0', max_length=1)),
                ('cfop_venda_dentro_estado', models.CharField(blank=True, help_text='CFOP padrão para venda dentro do estado.', max_length=4, null=True)),
                ('cfop_venda_fora_estado', models.CharField(blank=True, help_text='CFOP padrão para venda fora do estado.', max_length=4, null=True)),
                ('csosn_icms', models.CharField(blank=True, help_text='CSOSN/CST ICMS padrão do produto em vendas.', max_length=3, null=True)),
                ('aliquota_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota ICMS padrão para operações internas (quando aplicável).', max_digits=5)),
                ('cst_pis', models.CharField(blank=True, help_text='CST PIS padrão do produto.', max_length=2, null=True)),
                ('cst_cofins', models.CharField(blank=True, help_text='CST COFINS padrão do produto.', max_length=2, null=True)),
                ('aliquota_pis', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota de PIS em percentual (ex: 1.65).', max_digits=5)),
                ('aliquota_cofins', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota de COFINS em percentual (ex: 7.60).', max_digits=5)),
                ('cst_ipi', models.CharField(blank=True, help_text='CST IPI padrão do produto.', max_length=2, null=True)),
                ('codigo_enquadramento_ipi', models.CharField(blank=True, help_text='Código de enquadramento legal do IPI (clEnq).', max_length=3, null=True)),
                ('aliquota_ipi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('aliquota_cbs_especifica', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota CBS específica do produto (sobrepõe a padrão do NCM quando as regras de CBS entrarem em vigor).', max_digits=5)),
                ('aliquota_ibs_especifica', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota IBS específica do produto (sobrepõe a padrão do NCM quando as regras de IBS entrarem em vigor).', max_digits=5)),
                ('permite_fracionar', models.BooleanField(default=False, help_text='Indica se o produto pode ser vendido fracionado (balança, peso etc).')),
                ('rastreavel', models.BooleanField(default=False, help_text='Indica se requer rastreabilidade/lote/série.')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem do produto para exibição no app.', null=True, upload_to='produtos/')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(help_text='Grupo/categoria do produto.', on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.grupoproduto')),
                ('ncm', models.ForeignKey(help_text='NCM do produto (obrigatório para NF-e/NFC-e).', on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='fiscal.ncm')),
                ('unidade_comercial', models.ForeignKey(help_text='Unidade de comercialização (uCom).', on_delete=django.db.models.deletion.PROTECT, related_name='produtos_comerciais', to='produtos.unidademedida')),
                ('unidade_tributavel', models.ForeignKey(help_text='Unidade tributável (uTrib).', on_delete=django.db.models.deletion.PROTECT, related_name='produtos_tributaveis', to='produtos.unidademedida')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoCodigoBarras',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, help_text='Valor literal do código de barras (apenas dígitos).', max_length=20, validators=[django.core.validators.RegexValidator(message='Código de barras deve conter apenas dígitos.', regex='^[0-9]{2,20}$')])),
                ('tipo', models.CharField(choices=[('EAN13', 'EAN-13'), ('EAN14', 'EAN-14 / DUN-14'), ('EAN8', 'EAN-8'), ('INTERNO', 'Código interno / proprietário'), ('OUTRO', 'Outro padrão')], default='EAN13', help_text='Tipo de código de barras (EAN-13, EAN-14, interno, etc).', max_length=10)),
                ('funcao', models.CharField(choices=[('COMERCIAL', 'Código de barras de venda (cEAN)'), ('TRIBUTAVEL', 'Código de barras unidade tributável (cEANTrib)'), ('AMBOS', 'Usado tanto como cEAN quanto cEANTrib'), ('OUTRO', 'Apenas referência interna / outro uso')], default='COMERCIAL', help_text='Papel principal deste código para NF-e/NFC-e.', max_length=15)),
                ('principal', models.BooleanField(default=False, help_text='Indica se este é o código de barras principal do produto para a função informada.')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(help_text='Produto ao qual este código de barras pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='codigos_barras', to='produtos.produto')),
                ('unidade', models.ForeignKey(blank=True, help_text='Unidade de medida associada a este código, se houver (ex: CX, UN).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_barras', to='produtos.unidademedida')),
            ],
            options={
                'verbose_name': 'Código de Barras do Produto',
                'verbose_name_plural': 'Códigos de Barras dos Produtos',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='idx_prod_cod_barras_codigo'), models.Index(fields=['produto', 'ativo'], name='idx_prod_cod_barras_ativo'), models.Index(fields=['produto', 'funcao', 'ativo'], name='idx_pcb_func_atv')],
            },
        ),
        migrations.AddConstraint(
            model_name='produtocodigobarras',
            constraint=models.UniqueConstraint(fields=('produto', 'codigo'), name='uniq_produto_codigo_barras'),
        ),
        migrations.AddConstraint(
            model_name='produtocodigobarras',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('produto', 'funcao'), name='uniq_principal_por_funcao_produto'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['codigo_interno'], name='idx_prod_codigo_interno'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['descricao'], name='idx_prod_descricao'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ativo', 'grupo'], name='idx_prod_ativo_grupo'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ncm'], name='idx_prod_ncm'),
        ),
    ]
