# Generated by Django 5.0.6 on 2025-11-24 20:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Preço de venda padrão do produto.', max_digits=12),
        ),
    ]
