# Generated by Django 5.0.6 on 2025-11-24 23:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_preco_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='percentual_desconto_maximo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual máximo de desconto permitido neste produto.', max_digits=5),
        ),
    ]
