# Generated by Django 5.0.6 on 2025-11-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_percentual_desconto_maximo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='percentual_desconto_maximo',
            new_name='desconto_maximo_percentual',
        ),
    ]
