# Generated by Django 5.0.6 on 2025-11-25 00:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_rename_percentual_desconto_maximo_produto_desconto_maximo_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='desconto_maximo_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Percentual máximo de desconto permitido neste produto.', max_digits=5, null=True),
        ),
    ]
