# Generated by Django 5.0.6 on 2025-11-24 23:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoDesconto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, help_text='Código interno do motivo de desconto (ex.: PROMO10, QUEBRA, FIDELIDADE).', max_length=20, unique=True)),
                ('descricao', models.CharField(help_text='Descrição legível do motivo de desconto.', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motivo de Desconto',
                'verbose_name_plural': 'Motivos de Desconto',
                'db_table': 'motivo_desconto',
                'ordering': ['codigo'],
            },
        ),
    ]
