# Generated by Django 5.0.6 on 2025-11-24 20:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0002_filialnfceconfig_external_api_key_alias_and_more'),
        #('metodoPagamento', '0001_initial'),
        ('produtos', '0001_initial'),
        ('terminal', '0002_terminal_permite_tef_terminal_tef_terminal_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_venda', models.CharField(choices=[('VENDA', 'Venda normal (com documento fiscal)'), ('ORCAMENTO', 'Orçamento / Pré-venda (sem emissão fiscal)'), ('INTERNO', 'Pedido interno / consumo próprio')], default='VENDA', help_text='Tipo de venda (normal, orçamento, pedido interno).', max_length=20)),
                ('documento_fiscal_tipo', models.CharField(choices=[('NFCE', 'NFC-e'), ('NFE', 'NF-e'), ('NENHUM', 'Nenhum (orcamento/pedido interno)')], default='NFCE', help_text='Tipo de documento fiscal associado (NFC-e, NF-e ou nenhum).', max_length=10)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta (montando carrinho)'), ('AG_PAG', 'Aguardando pagamento'), ('PG_PROC', 'Pagamento em processamento'), ('PG_OK', 'Pagamento confirmado'), ('AG_DOC', 'Aguardando emissão fiscal'), ('ERRO_FISCAL', 'Erro fiscal'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ABERTA', help_text='Estado atual da venda no fluxo de negócio.', max_length=20)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_liquido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_troco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='Identificador único da requisição de venda (para evitar duplicidades em cenários de queda de conexão).', max_length=64, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(help_text='Filial em que a venda foi realizada.', on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='filial.filial')),
                ('operador', models.ForeignKey(help_text='Usuário operador que abriu/fechou a venda.', on_delete=django.db.models.deletion.PROTECT, related_name='vendas_operadas', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(help_text='Terminal (PDV) responsável pela venda.', on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='terminal.terminal')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'venda',
            },
        ),
        migrations.CreateModel(
            name='VendaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Descrição do produto no momento da venda (snapshot).', max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantidade vendida.', max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=6, help_text='Preço unitário praticado na venda.', max_digits=12)),
                ('total_bruto', models.DecimalField(decimal_places=2, help_text='Total bruto do item (quantidade x preço unitário).', max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de desconto concedido neste item.', max_digits=12)),
                ('total_liquido', models.DecimalField(decimal_places=2, help_text='Total líquido do item (bruto - desconto).', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(help_text='Produto vendido.', on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='produtos.produto')),
                ('venda', models.ForeignKey(help_text='Venda à qual este item pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Venda',
                'db_table': 'venda_item',
            },
        ),
        migrations.CreateModel(
            name='VendaPagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor pago com este método.', max_digits=12)),
                ('valor_troco', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Parte do valor que retornou como troco (se aplicável).', max_digits=12)),
                ('utiliza_tef', models.BooleanField(default=False, help_text='Snapshot de se o método utilizava TEF no momento do pagamento.')),
                ('tef_status', models.CharField(blank=True, help_text='Status TEF resumido para este pagamento (APROVADO, NEGADO, ERRO, NAO_APLICA).', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metodo_pagamento', models.ForeignKey(help_text='Método de pagamento utilizado.', on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_venda', to='metodoPagamento.metodopagamento')),
                ('venda', models.ForeignKey(help_text='Venda à qual este pagamento pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Pagamento de Venda',
                'verbose_name_plural': 'Pagamentos de Venda',
                'db_table': 'venda_pagamento',
            },
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['filial'], name='idx_venda_filial'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['terminal'], name='idx_venda_terminal'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['status'], name='idx_venda_status'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['request_id'], name='idx_venda_request_id'),
        ),
        migrations.AddIndex(
            model_name='vendaitem',
            index=models.Index(fields=['venda'], name='idx_vendaitem_venda'),
        ),
        migrations.AddIndex(
            model_name='vendapagamento',
            index=models.Index(fields=['venda'], name='idx_vendapgto_venda'),
        ),
        migrations.AddIndex(
            model_name='vendapagamento',
            index=models.Index(fields=['metodo_pagamento'], name='idx_vendapgto_metodo'),
        ),
    ]
