# Generated by Django 5.0.6 on 2025-11-24 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocoes', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendaitem',
            name='desconto',
        ),
        migrations.AddField(
            model_name='venda',
            name='desconto_global_aprovado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que aprovou o desconto global, quando excedeu o limite do operador.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_com_desconto_aprovado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venda',
            name='motivo_desconto_global',
            field=models.ForeignKey(blank=True, help_text='Motivo do desconto global da venda.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_com_desconto_global', to='promocoes.motivodesconto'),
        ),
        migrations.AddField(
            model_name='venda',
            name='percentual_desconto_global',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de desconto global aplicado sobre o total da venda antes da distribuição por itens. Opcional; pode ser 0/NULL caso apenas descontos por item sejam usados.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='desconto_aprovado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que aprovou o desconto neste item, quando foi necessário exceder o limite do operador.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='descontos_itens_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='motivo_desconto',
            field=models.ForeignKey(blank=True, help_text='Motivo do desconto aplicado neste item.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda_com_desconto', to='promocoes.motivodesconto'),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='percentual_desconto_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de desconto aplicado sobre o preço unitário do produto neste item. Usado para auditoria e validação de limites.', max_digits=5, null=True),
        ),
    ]
