# Generated by Django 5.0.6 on 2025-11-25 17:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodoPagamento', '0001_initial'),
        ('vendas', '0002_remove_vendaitem_desconto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendapagamento',
            name='tef_status',
        ),
        migrations.RemoveField(
            model_name='vendapagamento',
            name='valor',
        ),
        migrations.AddField(
            model_name='vendapagamento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendapagamento',
            name='mensagem_retorno',
            field=models.CharField(blank=True, help_text='Mensagem resumida do retorno da adquirente/TEF ou de validação.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendapagamento',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pendente'), ('AUT', 'Autorizado'), ('NEG', 'Negado'), ('CAN', 'Cancelado'), ('EST', 'Estornado'), ('ERR', 'Erro de Processamento')], db_index=True, default='PEN', help_text='Status do pagamento no fluxo de autorização.', max_length=3),
        ),
        migrations.AddField(
            model_name='vendapagamento',
            name='valor_autorizado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor efetivamente autorizado para este pagamento.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vendapagamento',
            name='valor_solicitado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor solicitado pelo operador para este pagamento.', max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendapagamento',
            name='metodo_pagamento',
            field=models.ForeignKey(help_text='Método de pagamento utilizado.', on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='metodoPagamento.metodopagamento'),
        ),
        migrations.AlterField(
            model_name='vendapagamento',
            name='utiliza_tef',
            field=models.BooleanField(default=False, help_text='Snapshot se o método utilizava TEF no momento do pagamento.'),
        ),
        migrations.AlterField(
            model_name='vendapagamento',
            name='valor_troco',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Parte do valor que retornou como troco neste pagamento.', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='vendapagamento',
            index=models.Index(fields=['status'], name='idx_vendapgto_status'),
        ),
    ]
