# Generated by Django 5.0.6 on 2025-11-25 19:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_remove_vendapagamento_tef_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaitem',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor absoluto de desconto aplicado neste item.', max_digits=12),
        ),
    ]
