# Generated by Django 5.0.6 on 2025-11-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_vendaitem_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cpf_na_nota',
            field=models.CharField(blank=True, help_text='CPF do consumidor para impressão na NFC-e/NF-e. Pode ser informado com ou sem máscara.', max_length=14, null=True),
        ),
    ]
