# Generated by Django 5.0.6 on 2025-11-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_venda_cpf_na_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendapagamento',
            name='codigo_autorizacao',
            field=models.CharField(blank=True, help_text='Código de autorização devolvido pela adquirente.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vendapagamento',
            name='codigo_retorno',
            field=models.CharField(blank=True, help_text='Código de retorno da transação TEF.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='vendapagamento',
            name='nsu_host',
            field=models.CharField(blank=True, help_text='NSU/identificador da transação no host/adquirente.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='vendapagamento',
            name='nsu_sitef',
            field=models.CharField(blank=True, help_text='NSU/identificador da transação no TEF (ex.: SITEF).', max_length=64, null=True),
        ),
    ]
