# Generated by Django 5.0.6 on 2025-11-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_vendapagamento_codigo_autorizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='codigo_erro_fiscal',
            field=models.CharField(blank=True, help_text='Último código de erro fiscal retornado pela SEFAZ / API fiscal.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='mensagem_erro_fiscal',
            field=models.CharField(blank=True, help_text='Última mensagem de erro fiscal resumida.', max_length=255, null=True),
        ),
    ]
