# Generated by Django 5.0.6 on 2025-11-26 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_venda_codigo_erro_fiscal_venda_mensagem_erro_fiscal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Vendedor associado à venda, se aplicável.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_vendidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
