# Generated by Django 5.0.6 on 2025-11-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_venda_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='identificacao_cliente',
            field=models.CharField(blank=True, help_text='Identificação adicional do cliente (nome, código, etc.) para impressão na NFC-e/NF-e.', max_length=100, null=True),
        ),
    ]
