# Generated by Django 5.0.6 on 2025-11-27 13:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_venda_identificacao_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaitem',
            name='aliquota_cbs_item',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota de CBS aplicada ao item.', max_digits=5),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='aliquota_cofins_item',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota de COFINS aplicada ao item.', max_digits=5),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='aliquota_ibs_item',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota de IBS aplicada ao item.', max_digits=5),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='aliquota_icms_item',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota de ICMS aplicada ao item.', max_digits=5),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='aliquota_ipi_item',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota de IPI aplicada ao item.', max_digits=5),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='aliquota_pis_item',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota de PIS aplicada ao item.', max_digits=5),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='cest_codigo',
            field=models.CharField(blank=True, help_text='Código CEST aplicado ao item no momento da venda, quando aplicável.', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='cfop_aplicado',
            field=models.CharField(blank=True, help_text='CFOP aplicado a este item na operação.', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='csosn_icms_item',
            field=models.CharField(blank=True, help_text='CSOSN/CST ICMS aplicado ao item.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='cst_cofins_item',
            field=models.CharField(blank=True, help_text='CST COFINS aplicado ao item.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='cst_ipi_item',
            field=models.CharField(blank=True, help_text='CST IPI aplicado ao item.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='cst_pis_item',
            field=models.CharField(blank=True, help_text='CST PIS aplicado ao item.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='ncm_codigo',
            field=models.CharField(blank=True, help_text='Código NCM aplicado ao item no momento da venda.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendaitem',
            name='origem_mercadoria_item',
            field=models.CharField(blank=True, help_text='Origem da mercadoria (0–8) capturada no momento da venda.', max_length=1, null=True),
        ),
    ]
