# Generated by Django 5.0.6 on 2025-11-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_vendaitem_aliquota_cbs_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendaitem',
            name='motivo_desconto',
            field=models.TextField(blank=True, help_text='Motivo do desconto aplicado neste item.', null=True),
        ),
    ]
