# Generated by Django 5.0.6 on 2025-11-27 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_cest_ncm_ncm_uniq_ncm_codigo_vigencia_inicio_and_more'),
        ('vendas', '0011_alter_vendaitem_motivo_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='nfce_documento',
            field=models.ForeignKey(blank=True, help_text='Documento NFC-e gerado para esta venda, quando aplicável.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_origem', to='fiscal.nfcedocumento'),
        ),
    ]
