# Generated by Django 5.0.6 on 2025-11-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
        ('vendas', '0012_venda_nfce_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='caixa',
            field=models.ForeignKey(blank=True, help_text='Caixa em que a venda foi realizada.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='caixa.caixa'),
        ),
    ]
