# Generated by Django 5.0.6 on 2025-11-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_userperfil_alter_user_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userperfil',
            old_name='maximo_desconto_percentual',
            new_name='desconto_maximo_percentual',
        ),
    ]
