# Generated by Django 5.0.6 on 2025-11-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_userperfil_desconto_maximo_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperfil',
            name='desconto_maximo_percentual',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual máximo de desconto que um usuário com este perfil pode conceder.', max_digits=5),
        ),
    ]
