# Generated by Django 5.0.6 on 2025-11-12 01:54

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NfceNumeroReserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terminal_id', models.UUIDField()),
                ('filial_id', models.UUIDField()),
                ('serie', models.PositiveIntegerField()),
                ('numero', models.PositiveIntegerField()),
                ('request_id', models.UUIDField(unique=True)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'nfce_numero_reserva',
                'indexes': [models.Index(fields=['terminal_id', 'serie'], name='nfce_numero_termina_c2e46c_idx'), models.Index(fields=['filial_id'], name='nfce_numero_filial__8dc944_idx')],
            },
        ),
    ]
