# Generated by Django 5.0.6 on 2025-11-18 14:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0001_initial'),
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfceDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField()),
                ('serie', models.PositiveIntegerField()),
                ('chave_acesso', models.CharField(max_length=47, unique=True)),
                ('protocolo', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(max_length=32)),
                ('request_id', models.UUIDField(unique=True)),
                ('xml_autorizado', models.TextField(blank=True, null=True)),
                ('raw_sefaz_response', models.JSONField(blank=True, null=True)),
                ('mensagem_sefaz', models.TextField(blank=True, null=True)),
                ('ambiente', models.CharField(default='homolog', max_length=20)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('em_contingencia', models.BooleanField(default=False)),
                ('contingencia_ativada_em', models.DateTimeField(blank=True, null=True)),
                ('contingencia_motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('contingencia_regularizada_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfce_documentos', to='filial.filial')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfce_documentos', to='terminal.terminal')),
            ],
            options={
                'db_table': 'nfce_documento',
            },
        ),
        migrations.CreateModel(
            name='NfceAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('tenant_id', models.CharField(blank=True, help_text='Identificação do tenant (ex: schema_name ou CNPJ raiz).', max_length=64, null=True)),
                ('filial_id', models.UUIDField()),
                ('terminal_id', models.UUIDField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('request_id', models.UUIDField()),
                ('codigo_retorno', models.CharField(blank=True, max_length=10, null=True)),
                ('mensagem_retorno', models.TextField(blank=True, null=True)),
                ('xml_autorizado', models.TextField(blank=True, null=True)),
                ('raw_sefaz_response', models.JSONField(blank=True, null=True)),
                ('ambiente', models.CharField(blank=True, max_length=20, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nfce_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='fiscal.nfcedocumento')),
            ],
            options={
                'db_table': 'nfce_auditoria',
            },
        ),
        migrations.CreateModel(
            name='NfceInutilizacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serie', models.PositiveIntegerField()),
                ('numero_inicial', models.PositiveIntegerField()),
                ('numero_final', models.PositiveIntegerField()),
                ('request_id', models.UUIDField(unique=True)),
                ('protocolo', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(default='inutilizada', max_length=32)),
                ('motivo', models.TextField()),
                ('xml_envio', models.TextField(blank=True, null=True)),
                ('xml_resposta', models.TextField(blank=True, null=True)),
                ('raw_sefaz_response', models.JSONField(blank=True, null=True)),
                ('ambiente', models.CharField(blank=True, max_length=20, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfce_inutilizacoes', to='filial.filial')),
            ],
            options={
                'db_table': 'nfce_inutilizacao',
            },
        ),
        migrations.CreateModel(
            name='NfceNumeroReserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terminal_id', models.UUIDField()),
                ('filial_id', models.UUIDField()),
                ('serie', models.PositiveIntegerField()),
                ('numero', models.PositiveIntegerField()),
                ('request_id', models.UUIDField(unique=True)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'nfce_numero_reserva',
                'indexes': [models.Index(fields=['terminal_id', 'serie'], name='nfce_numero_termina_c2e46c_idx'), models.Index(fields=['filial_id'], name='nfce_numero_filial__8dc944_idx')],
            },
        ),
        migrations.CreateModel(
            name='NfcePreEmissao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filial_id', models.UUIDField()),
                ('terminal_id', models.UUIDField()),
                ('numero', models.BigIntegerField()),
                ('serie', models.IntegerField()),
                ('request_id', models.UUIDField(unique=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nfce_pre_emissao',
                'unique_together': {('filial_id', 'terminal_id', 'serie', 'numero')},
            },
        ),
        migrations.AddIndex(
            model_name='nfcedocumento',
            index=models.Index(fields=['request_id'], name='nfce_docume_request_77bb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='nfcedocumento',
            index=models.Index(fields=['chave_acesso'], name='nfce_docume_chave_a_903fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='nfcedocumento',
            index=models.Index(fields=['filial', 'serie', 'numero'], name='nfce_docume_filial__fadf79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nfcedocumento',
            unique_together={('filial', 'serie', 'numero')},
        ),
        migrations.AddIndex(
            model_name='nfceauditoria',
            index=models.Index(fields=['request_id'], name='nfce_audito_request_ded35f_idx'),
        ),
        migrations.AddIndex(
            model_name='nfceauditoria',
            index=models.Index(fields=['tipo_evento'], name='nfce_audito_tipo_ev_e78961_idx'),
        ),
        migrations.AddIndex(
            model_name='nfceauditoria',
            index=models.Index(fields=['tenant_id'], name='nfce_audito_tenant__3293d7_idx'),
        ),
        migrations.AddIndex(
            model_name='nfceinutilizacao',
            index=models.Index(fields=['filial', 'serie', 'numero_inicial', 'numero_final'], name='nfce_inutil_filial__9f6cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='nfceinutilizacao',
            index=models.Index(fields=['request_id'], name='nfce_inutil_request_31f8cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nfceinutilizacao',
            unique_together={('filial', 'serie', 'numero_inicial', 'numero_final')},
        ),
    ]
