# Generated by Django 5.0.6 on 2025-11-19 19:41

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEST',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, help_text='Código CEST (7 dígitos).', max_length=7, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('vigencia_inicio', models.DateField(blank=True, null=True)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CEST',
                'verbose_name_plural': 'CESTs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='NCM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, help_text='Código NCM (geralmente 8 dígitos, somente números).', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{2,10}$', 'NCM deve ter apenas dígitos.')])),
                ('descricao', models.CharField(max_length=255)),
                ('ex_tipi', models.CharField(blank=True, help_text='EX TIPI quando aplicável.', max_length=3, null=True)),
                ('aliquota_importacao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota de Imposto de Importação associada ao NCM, quando aplicável.', max_digits=5)),
                ('aliquota_ipi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota de IPI padrão para este NCM, quando aplicável.', max_digits=5)),
                ('aliquota_pis', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota PIS padrão (cumulativo/não cumulativo conforme regime).', max_digits=5)),
                ('aliquota_cofins', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota COFINS padrão.', max_digits=5)),
                ('vigencia_inicio', models.DateField(blank=True, help_text='Data de início de vigência deste NCM (segundo tabela oficial).', null=True)),
                ('vigencia_fim', models.DateField(blank=True, help_text='Data de fim de vigência (quando revogado/substituído).', null=True)),
                ('versao_tabela', models.CharField(blank=True, help_text='Versão/ano da tabela NCM/Tipi utilizada.', max_length=20)),
                ('aliquota_cbs_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota CBS prevista para este NCM (campo de preparação para novas regras tributárias a partir de 2026).', max_digits=5)),
                ('aliquota_ibs_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alíquota IBS prevista para este NCM (campo de preparação para novas regras tributárias a partir de 2026).', max_digits=5)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NCM',
                'verbose_name_plural': 'NCMs',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='ncm',
            constraint=models.UniqueConstraint(fields=('codigo', 'vigencia_inicio'), name='uniq_ncm_codigo_vigencia_inicio'),
        ),
        migrations.AddField(
            model_name='cest',
            name='ncms',
            field=models.ManyToManyField(blank=True, help_text='Lista de NCMs cobertos por este CEST.', related_name='cests', to='fiscal.ncm'),
        ),
    ]
