# Generated by Django 5.0.6 on 2025-11-13 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfcePreEmissao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filial_id', models.UUIDField()),
                ('terminal_id', models.UUIDField()),
                ('numero', models.BigIntegerField()),
                ('serie', models.IntegerField()),
                ('request_id', models.UUIDField(unique=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nfce_pre_emissao',
                'unique_together': {('filial_id', 'terminal_id', 'serie', 'numero')},
            },
        ),
    ]
