# Generated by Django 5.0.6 on 2025-11-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_cest_ncm_ncm_uniq_ncm_codigo_vigencia_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfcenumeroreserva',
            name='codigo_retorno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nfcenumeroreserva',
            name='hash_payload_enviado',
            field=models.CharField(blank=True, help_text='Hash SHA256 do payload_enviado, usado para idempotência e reconciliação.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='nfcenumeroreserva',
            name='mensagem_retorno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfcenumeroreserva',
            name='payload_enviado',
            field=models.JSONField(blank=True, help_text='Payload bruto enviado ao parceiro fiscal (XML/JSON).', null=True),
        ),
        migrations.AddField(
            model_name='nfcenumeroreserva',
            name='raw_sefaz_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfcenumeroreserva',
            name='xml_autorizado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
