# Generated by Django 5.0.6 on 2025-11-16 12:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
        ('fiscal', '0002_nfcepreemissao'),
        ('terminal', '0002_terminal_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfceDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField()),
                ('serie', models.PositiveIntegerField()),
                ('chave_acesso', models.CharField(max_length=44, unique=True)),
                ('protocolo', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(max_length=32)),
                ('request_id', models.UUIDField(unique=True)),
                ('xml_autorizado', models.TextField(blank=True, null=True)),
                ('raw_sefaz_response', models.JSONField(blank=True, null=True)),
                ('mensagem_sefaz', models.TextField(blank=True, null=True)),
                ('ambiente', models.CharField(default='homolog', max_length=20)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfce_documentos', to='filial.filial')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfce_documentos', to='terminal.terminal')),
            ],
            options={
                'db_table': 'nfce_documento',
            },
        ),
        migrations.CreateModel(
            name='NfceAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(max_length=50)),
                ('tenant_id', models.CharField(blank=True, help_text='Identificação do tenant (ex: schema_name ou CNPJ raiz).', max_length=64, null=True)),
                ('filial_id', models.UUIDField()),
                ('terminal_id', models.UUIDField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('request_id', models.UUIDField()),
                ('codigo_retorno', models.CharField(blank=True, max_length=10, null=True)),
                ('mensagem_retorno', models.TextField(blank=True, null=True)),
                ('xml_autorizado', models.TextField(blank=True, null=True)),
                ('raw_sefaz_response', models.JSONField(blank=True, null=True)),
                ('ambiente', models.CharField(blank=True, max_length=20, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nfce_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='fiscal.nfcedocumento')),
            ],
            options={
                'db_table': 'nfce_auditoria',
            },
        ),
        migrations.AddIndex(
            model_name='nfcedocumento',
            index=models.Index(fields=['request_id'], name='nfce_docume_request_77bb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='nfcedocumento',
            index=models.Index(fields=['chave_acesso'], name='nfce_docume_chave_a_903fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='nfcedocumento',
            index=models.Index(fields=['filial', 'serie', 'numero'], name='nfce_docume_filial__fadf79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nfcedocumento',
            unique_together={('filial', 'serie', 'numero')},
        ),
        migrations.AddIndex(
            model_name='nfceauditoria',
            index=models.Index(fields=['request_id'], name='nfce_audito_request_ded35f_idx'),
        ),
        migrations.AddIndex(
            model_name='nfceauditoria',
            index=models.Index(fields=['tipo_evento'], name='nfce_audito_tipo_ev_e78961_idx'),
        ),
        migrations.AddIndex(
            model_name='nfceauditoria',
            index=models.Index(fields=['tenant_id'], name='nfce_audito_tenant__3293d7_idx'),
        ),
    ]
