# Generated by Django 5.0.6 on 2025-11-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_nfcenumeroreserva_codigo_retorno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfcenumeroreserva',
            name='hash_payload_enviado',
        ),
        migrations.RemoveField(
            model_name='nfcenumeroreserva',
            name='payload_enviado',
        ),
        migrations.AddField(
            model_name='nfcedocumento',
            name='hash_payload_enviado',
            field=models.CharField(blank=True, help_text='Hash SHA256 do payload_enviado, usado para idempotência e reconciliação.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='nfcedocumento',
            name='payload_enviado',
            field=models.JSONField(blank=True, help_text='Payload bruto enviado ao parceiro fiscal (XML/JSON).', null=True),
        ),
    ]
