# Generated by Django 5.0.6 on 2025-11-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_nfcedocumento_nfceauditoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcedocumento',
            name='chave_acesso',
            field=models.CharField(max_length=47, unique=True),
        ),
    ]
