# Generated by Django 5.0.6 on 2025-11-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_remove_nfcenumeroreserva_hash_payload_enviado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfceauditoria',
            name='codigo_retorno',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
