# Generated by Django 5.0.6 on 2025-11-16 15:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
        ('fiscal', '0004_alter_nfcedocumento_chave_acesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfceInutilizacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serie', models.PositiveIntegerField()),
                ('numero_inicial', models.PositiveIntegerField()),
                ('numero_final', models.PositiveIntegerField()),
                ('request_id', models.UUIDField(unique=True)),
                ('protocolo', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(default='inutilizada', max_length=32)),
                ('motivo', models.TextField()),
                ('xml_envio', models.TextField(blank=True, null=True)),
                ('xml_resposta', models.TextField(blank=True, null=True)),
                ('raw_sefaz_response', models.JSONField(blank=True, null=True)),
                ('ambiente', models.CharField(blank=True, max_length=20, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfce_inutilizacoes', to='filial.filial')),
            ],
            options={
                'db_table': 'nfce_inutilizacao',
                'indexes': [models.Index(fields=['filial', 'serie', 'numero_inicial', 'numero_final'], name='nfce_inutil_filial__9f6cfb_idx'), models.Index(fields=['request_id'], name='nfce_inutil_request_31f8cd_idx')],
                'unique_together': {('filial', 'serie', 'numero_inicial', 'numero_final')},
            },
        ),
    ]
