# Generated by Django 5.0.6 on 2025-11-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0005_nfceinutilizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfcedocumento',
            name='contingencia_ativada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfcedocumento',
            name='contingencia_motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nfcedocumento',
            name='contingencia_regularizada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfcedocumento',
            name='em_contingencia',
            field=models.BooleanField(default=False),
        ),
    ]
