# Generated by Django 5.0.6 on 2025-11-11 00:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filial_id', models.UUIDField()),
                ('identificador', models.CharField(max_length=40, unique=True)),
                ('serie', models.IntegerField(default=1)),
                ('numero_atual', models.IntegerField(default=0)),
                ('permite_suprimento', models.BooleanField(default=True)),
                ('permite_sangria', models.BooleanField(default=True)),
            ],
        ),
    ]
