# Generated by Django 5.0.6 on 2025-11-18 14:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identificador', models.CharField(help_text='Identificador único do terminal (ex.: PDV-01, CAIXA-01).', max_length=40)),
                ('permite_suprimento', models.BooleanField(default=True, help_text='Define se o terminal permite operação de suprimento.')),
                ('permite_sangria', models.BooleanField(default=True, help_text='Define se o terminal permite operação de sangria.')),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Indica se o terminal está ativo para uso.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(help_text='Filial à qual este terminal pertence.', on_delete=django.db.models.deletion.PROTECT, related_name='terminais', to='filial.filial')),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminais',
                'ordering': ['filial__nome_fantasia', 'identificador'],
                'indexes': [models.Index(fields=['filial'], name='idx_terminal_filial'), models.Index(fields=['ativo'], name='idx_terminal_ativo')],
            },
        ),
        migrations.AddConstraint(
            model_name='terminal',
            constraint=models.UniqueConstraint(fields=('filial', 'identificador'), name='uniq_terminal_filial_identificador'),
        ),
    ]
