# Generated by Django 5.0.6 on 2025-11-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
