# Generated by Django 5.0.6 on 2025-11-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='permite_tef',
            field=models.BooleanField(default=True, help_text='Indica se este terminal está habilitado para uso de TEF.'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='tef_terminal_id',
            field=models.CharField(blank=True, help_text="Identificador do terminal no TEF (SITEF ou outro). Em muitas integrações, corresponde ao 'PDV' configurado no servidor TEF.", max_length=32, null=True),
        ),
    ]
