# Generated by Django 5.0.6 on 2025-11-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_terminal_permite_tef_terminal_tef_terminal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='percentual_maximo_desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual máximo de desconto permitido neste terminal.', max_digits=5),
        ),
    ]
