# Generated by Django 5.0.6 on 2025-11-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0004_rename_percentual_maximo_desconto_terminal_desconto_maximo_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='desconto_maximo_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Percentual máximo de desconto permitido neste terminal.', max_digits=5, null=True),
        ),
    ]
