# Generated by Django 5.0.6 on 2025-11-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_alter_terminal_desconto_maximo_percentual'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='solicitar_senha_estorno',
            field=models.BooleanField(default=False, help_text='Se marcado, exige aprovação/senha de supervisor para estornar pagamentos no PDV. Se desmarcado, qualquer operador com acesso ao caixa pode estornar.'),
        ),
    ]
