# Generated by Django 5.0.6 on 2025-11-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0006_terminal_solicitar_senha_estorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='solicita_vendedor',
            field=models.BooleanField(default=False, help_text='Se marcado, o operador deve informar o vendedor para cada venda.'),
        ),
    ]
