# Generated by Django 5.0.6 on 2025-11-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0007_terminal_solicita_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='solicita_cpf_cliente',
            field=models.BooleanField(default=False, help_text='Se marcado, o operador deve informar o CPF do cliente para cada venda.'),
        ),
    ]
