# Generated by Django 5.0.6 on 2025-11-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0008_terminal_solicita_cpf_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='abre_fecha_caixa',
            field=models.BooleanField(default=True, help_text='Define se o terminal tem permissão para abrir e fechar caixa.'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='solicita_identificacao_cliente',
            field=models.BooleanField(default=False, help_text='Se marcado, o operador deve informar a identificação do cliente para cada venda.'),
        ),
    ]
