# Generated by Django 5.0.6 on 2025-11-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0009_terminal_abre_fecha_caixa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='desconto_automatico',
            field=models.BooleanField(default=False, help_text='Se marcado, aplica descontos automáticos conforme regras da filial.'),
        ),
    ]
