# Generated by Django 5.0.6 on 2025-11-28 13:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0008_filialfiscalconfig_aliquota_cofins_and_more'),
        ('terminal', '0010_terminal_desconto_automatico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('saldo_final_calculado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('saldo_final_informado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('diferenca', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('aberto_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas', to='filial.filial')),
                ('operador_abertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas_abertos', to=settings.AUTH_USER_MODEL)),
                ('operador_fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixas_fechados', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas', to='terminal.terminal')),
            ],
            options={
                'db_table': 'caixa',
            },
        ),
        migrations.CreateModel(
            name='Sangria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sangrias', to='caixa.caixa')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'caixa_sangria',
            },
        ),
        migrations.CreateModel(
            name='Suprimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suprimentos', to='caixa.caixa')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'caixa_suprimento',
            },
        ),
        migrations.AddIndex(
            model_name='caixa',
            index=models.Index(fields=['filial', 'terminal', 'status'], name='caixa_filial__805c1a_idx'),
        ),
    ]
