# Generated by Django 5.0.6 on 2025-11-18 14:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do bairro (xBairro).', max_length=60)),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'ordering': ['municipio__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome do município (xMun na NFe).', max_length=60)),
                ('codigo_ibge', models.CharField(help_text='Código IBGE do município (7 dígitos, cMun na NFe).', max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)])),
                ('codigo_siafi', models.CharField(blank=True, help_text='Código SIAFI do município (se aplicável).', max_length=10)),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ['uf__sigla', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('RUA', 'Rua'), ('AV', 'Avenida'), ('ROD', 'Rodovia'), ('OUTROS', 'Outros')], default='RUA', help_text='Tipo de logradouro (Rua, Avenida, Rodovia, etc.).', max_length=10)),
                ('nome', models.CharField(help_text="Nome do logradouro (sem o tipo). Ex.: 'Paulista'.", max_length=80)),
                ('cep', models.CharField(help_text='CEP base do logradouro (somente números).', max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('bairro', models.ForeignKey(help_text='Bairro em que este logradouro se encontra.', on_delete=django.db.models.deletion.PROTECT, related_name='logradouros', to='enderecos.bairro')),
            ],
            options={
                'verbose_name': 'Logradouro',
                'verbose_name_plural': 'Logradouros',
                'ordering': ['bairro__municipio__nome', 'bairro__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(help_text="Número do endereço (nro). Use 'S/N' se sem número.", max_length=10)),
                ('complemento', models.CharField(blank=True, help_text='Complemento (xCpl), se houver.', max_length=60)),
                ('referencia', models.CharField(blank=True, help_text='Ponto de referência (uso interno, não vai na NF-e).', max_length=120)),
                ('cep', models.CharField(help_text='CEP completo (somente números).', max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('logradouro', models.ForeignKey(help_text='Logradouro (xLgr) do endereço.', on_delete=django.db.models.deletion.PROTECT, related_name='enderecos', to='enderecos.logradouro')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['logradouro__bairro__municipio__nome', 'logradouro__nome', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='bairro',
            name='municipio',
            field=models.ForeignKey(help_text='Município ao qual o bairro pertence.', on_delete=django.db.models.deletion.PROTECT, related_name='bairros', to='enderecos.municipio'),
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_nfe', models.CharField(help_text='Código do país conforme tabela NFe (ex.: 1058 para Brasil).', max_length=4, unique=True)),
                ('nome', models.CharField(help_text='Nome do país (xPais na NFe).', max_length=60, unique=True)),
                ('sigla2', models.CharField(blank=True, help_text='Sigla ISO alpha-2 (ex.: BR).', max_length=2)),
                ('sigla3', models.CharField(blank=True, help_text='Sigla ISO alpha-3 (ex.: BRA).', max_length=3)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['codigo_nfe'], name='idx_pais_codigo_nfe')],
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sigla', models.CharField(help_text='Sigla da UF (ex.: SP, RJ, MG).', max_length=2, unique=True)),
                ('nome', models.CharField(help_text='Nome da UF (ex.: São Paulo).', max_length=60, unique=True)),
                ('codigo_ibge', models.CharField(help_text='Código IBGE da UF (2 dígitos).', max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('pais', models.ForeignKey(help_text='País ao qual esta UF pertence (normalmente Brasil).', on_delete=django.db.models.deletion.PROTECT, related_name='ufs', to='enderecos.pais')),
            ],
            options={
                'verbose_name': 'UF',
                'verbose_name_plural': 'UFs',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='municipio',
            name='uf',
            field=models.ForeignKey(help_text='UF do município.', on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='enderecos.uf'),
        ),
        migrations.AddIndex(
            model_name='logradouro',
            index=models.Index(fields=['bairro'], name='idx_logradouro_bairro'),
        ),
        migrations.AddIndex(
            model_name='logradouro',
            index=models.Index(fields=['cep'], name='idx_logradouro_cep'),
        ),
        migrations.AddConstraint(
            model_name='logradouro',
            constraint=models.UniqueConstraint(fields=('tipo', 'nome', 'bairro'), name='uniq_logradouro_tipo_nome_bairro'),
        ),
        migrations.AddIndex(
            model_name='endereco',
            index=models.Index(fields=['cep'], name='idx_endereco_cep'),
        ),
        migrations.AddIndex(
            model_name='bairro',
            index=models.Index(fields=['municipio'], name='idx_bairro_municipio'),
        ),
        migrations.AddConstraint(
            model_name='bairro',
            constraint=models.UniqueConstraint(fields=('nome', 'municipio'), name='uniq_bairro_nome_municipio'),
        ),
        migrations.AddIndex(
            model_name='uf',
            index=models.Index(fields=['codigo_ibge'], name='idx_uf_codigo_ibge'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['uf'], name='idx_municipio_uf'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['codigo_ibge'], name='idx_municipio_codigo_ibge'),
        ),
        migrations.AddConstraint(
            model_name='municipio',
            constraint=models.UniqueConstraint(fields=('nome', 'uf'), name='uniq_municipio_nome_uf'),
        ),
    ]
