# Generated by Django 5.0.6 on 2025-11-25 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_endereco_created_at_endereco_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bairro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
