# Generated by Django 5.0.6 on 2025-11-24 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0002_filialnfceconfig_external_api_key_alias_and_more'),
        ('terminal', '0002_terminal_permite_tef_terminal_tef_terminal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TefConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('sitef', 'SiTef'), ('outro', 'Outro TEF')], default='sitef', help_text='Provider TEF utilizado (ex.: SiTef, outro).', max_length=20)),
                ('merchant_id', models.CharField(help_text='Identificador do lojista/afiliado no TEF (estabelecimento).', max_length=64)),
                ('store_id', models.CharField(blank=True, help_text='Identificador da loja/ponto de venda na adquirente/TEF (opcional).', max_length=64, null=True)),
                ('endpoint_base', models.URLField(blank=True, help_text='Endpoint/base da API TEF (quando TEF é IP/HTTP/Cloud).', null=True)),
                ('api_key_alias', models.CharField(blank=True, help_text='Alias/identificador da credencial TEF no cofre de segredos. Não armazena a chave em texto puro no banco.', max_length=128, null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se esta configuração TEF está ativa.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(help_text='Filial à qual esta configuração TEF pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='tef_configs', to='filial.filial')),
                ('terminal', models.ForeignKey(blank=True, help_text='Terminal específico para o qual esta configuração se aplica. Se vazio, a configuração é considerada padrão para todos os terminais da filial.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tef_configs', to='terminal.terminal')),
            ],
            options={
                'verbose_name': 'Configuração TEF',
                'verbose_name_plural': 'Configurações TEF',
                'db_table': 'tef_config',
                'indexes': [models.Index(fields=['filial'], name='idx_tef_config_filial'), models.Index(fields=['terminal'], name='idx_tef_config_terminal'), models.Index(fields=['provider'], name='idx_tef_config_provider')],
            },
        ),
        migrations.AddConstraint(
            model_name='tefconfig',
            constraint=models.UniqueConstraint(fields=('filial', 'terminal', 'provider'), name='uniq_tef_config_filial_terminal_provider'),
        ),
    ]
