# Generated by Django 5.0.6 on 2025-11-24 20:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TefTransacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('sitef', 'SiTef'), ('outro', 'Outro TEF')], default='sitef', help_text='Provider TEF utilizado nesta transação.', max_length=20)),
                ('status', models.CharField(choices=[('APROVADA', 'Aprovada'), ('NEGADA', 'Negada'), ('ERRO_COMUNICACAO', 'Erro de comunicação'), ('PENDENTE', 'Pendente')], help_text='Status final da transação TEF.', max_length=20)),
                ('nsu_host', models.CharField(blank=True, help_text='NSU/identificador da transação no host/adquirente.', max_length=64, null=True)),
                ('codigo_autorizacao', models.CharField(blank=True, help_text='Código de autorização devolvido pela adquirente.', max_length=64, null=True)),
                ('bandeira', models.CharField(blank=True, help_text='Bandeira do cartão (ex.: Visa, MasterCard).', max_length=32, null=True)),
                ('modalidade', models.CharField(blank=True, help_text='Modalidade (Crédito, Débito, Voucher etc).', max_length=32, null=True)),
                ('parcelas', models.PositiveSmallIntegerField(default=1, help_text='Quantidade de parcelas (1=à vista).')),
                ('valor_transacao', models.DecimalField(decimal_places=2, help_text='Valor autorizado na transação TEF.', max_digits=12)),
                ('pan_mascarado', models.CharField(blank=True, help_text='Número do cartão mascarado (ex.: **** **** **** 1234).', max_length=32, null=True)),
                ('codigo_retorno', models.CharField(blank=True, help_text='Código de retorno da transação TEF.', max_length=16, null=True)),
                ('mensagem_retorno', models.CharField(blank=True, help_text='Mensagem de retorno resumida.', max_length=255, null=True)),
                ('comprovante_cliente', models.TextField(blank=True, help_text='Texto do comprovante do cliente.', null=True)),
                ('comprovante_estabelecimento', models.TextField(blank=True, help_text='Texto do comprovante do estabelecimento.', null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Payload bruto retornado pelo TEF (sem dados sensíveis).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transação TEF',
                'verbose_name_plural': 'Transações TEF',
                'db_table': 'tef_transacao',
            },
        ),
    ]
