# Generated by Django 5.0.6 on 2025-11-24 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tef', '0002_teftransacao'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teftransacao',
            name='pagamento',
            field=models.OneToOneField(help_text='Pagamento de venda associado a esta transação TEF.', on_delete=django.db.models.deletion.CASCADE, related_name='tef_transacao', to='vendas.vendapagamento'),
        ),
        migrations.AddIndex(
            model_name='teftransacao',
            index=models.Index(fields=['provider'], name='idx_teftrans_provider'),
        ),
        migrations.AddIndex(
            model_name='teftransacao',
            index=models.Index(fields=['status'], name='idx_teftrans_status'),
        ),
    ]
