# Generated by Django 5.0.6 on 2025-11-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tef', '0003_teftransacao_pagamento_and_more'),
        ('vendas', '0005_venda_cpf_na_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='teftransacao',
            name='nsu_sitef',
            field=models.CharField(blank=True, help_text='NSU/identificador da transação no TEF (ex.: SITEF).', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='teftransacao',
            constraint=models.UniqueConstraint(condition=models.Q(('nsu_sitef__isnull', False)), fields=('nsu_sitef',), name='uq_teftransacao_nsu_sitef_not_null'),
        ),
        migrations.AddConstraint(
            model_name='teftransacao',
            constraint=models.UniqueConstraint(condition=models.Q(('nsu_host__isnull', False)), fields=('nsu_host',), name='uq_teftransacao_nsu_host_not_null'),
        ),
    ]
