# Generated by Django 5.0.6 on 2025-11-26 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0007_filial_ie_filial_im'),
        ('tef', '0004_teftransacao_nsu_sitef_and_more'),
        ('terminal', '0006_terminal_solicitar_senha_estorno'),
        ('vendas', '0006_vendapagamento_codigo_autorizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teftransacao',
            name='filial',
            field=models.ForeignKey(blank=True, help_text='Filial onde a transação foi realizada.', null=True, on_delete=django.db.models.deletion.PROTECT, to='filial.filial'),
        ),
        migrations.AddField(
            model_name='teftransacao',
            name='raw_request',
            field=models.TextField(blank=True, help_text='Dados brutos enviados na requisição TEF.', null=True),
        ),
        migrations.AddField(
            model_name='teftransacao',
            name='raw_response',
            field=models.TextField(blank=True, help_text='Dados brutos retornados pela requisição TEF.', null=True),
        ),
        migrations.AddField(
            model_name='teftransacao',
            name='terminal',
            field=models.ForeignKey(blank=True, help_text='Terminal onde a transação foi realizada.', null=True, on_delete=django.db.models.deletion.PROTECT, to='terminal.terminal'),
        ),
        migrations.AddField(
            model_name='teftransacao',
            name='valor_confirmado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor confirmado na transação TEF.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='teftransacao',
            name='venda',
            field=models.ForeignKey(blank=True, help_text='Venda associada a esta transação TEF.', null=True, on_delete=django.db.models.deletion.PROTECT, to='vendas.venda'),
        ),
    ]
