# Generated by Django 5.0.6 on 2025-11-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tef', '0005_teftransacao_filial_teftransacao_raw_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teftransacao',
            name='valor_transacao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor autorizado na transação TEF.', max_digits=12, null=True),
        ),
    ]
